In [1]:
import numpy as np
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
import PIL
import PIL.Image
import tensorflow as tf
import tensorflow_datasets as tfds
import pathlib
import matplotlib.pylab as plt
import random

In [8]:
A = tf.constant([2, 20, 30, 3, 6])
print(tf.math.argmax(A))

tf.Tensor(2, shape=(), dtype=int64)


In [9]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
print(tf.math.argmax(B, 0))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [10]:
print(tf.math.argmax(B, 1))

tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [11]:
C = tf.constant([0, 0, 0, 0])
print(tf.math.argmax(C))

tf.Tensor(0, shape=(), dtype=int64)


In [12]:
x = tf.constant([2, 4])
y = tf.constant(2)
print(tf.math.equal(x, y))

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [13]:
x = tf.constant([2, 4])
y = tf.constant([2, 4])
print(tf.math.equal(x, y))

tf.Tensor([ True  True], shape=(2,), dtype=bool)


In [14]:
dataset = tf.data.Dataset.range(8)
dataset = dataset.batch(3)
print(list(dataset.as_numpy_iterator()))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]


In [15]:
dataset = tf.data.Dataset.range(8)
dataset = dataset.batch(3, drop_remainder=True)
print(list(dataset.as_numpy_iterator()))

[array([0, 1, 2]), array([3, 4, 5])]


In [19]:
randomlist = [1,2,3,4,5]
random.shuffle(randomlist)
print(randomlist)

[5, 3, 1, 4, 2]


In [3]:
a = tf.constant([
  [[1, 2], [3, 4]],
  [[1, 2], [3, 4]]
])
print(tf.reduce_min(a))
#reduces all dimensions

tf.Tensor(1, shape=(), dtype=int32)


In [5]:
b = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tf.reduce_min(b, axis=0))
print(tf.reduce_min(b, axis=1))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)


In [6]:
print(tf.reduce_min(a, keepdims=True))

tf.Tensor([[[1]]], shape=(1, 1, 1), dtype=int32)


In [7]:
print(tf.math.reduce_min(a, axis=0, keepdims=True))

tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)


In [8]:
print(tf.version.VERSION)

2.6.0


In [9]:
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

SystemError: GPU device not found